version: "3"
services:
  akka-serverless-proxy:
    image: gcr.io/akkaserverless-public/akkaserverless-proxy:0.7.0-beta.19
    command: -Dconfig.resource=dev-mode.conf -Dakkaserverless.proxy.eventing.support=google-pubsub-emulator
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8080}
      PUBSUB_EMULATOR_HOST: gcloud-pubsub-emulator
  gcloud-pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:341.0.0
    command: gcloud beta emulators pubsub start --project=test --host-port=0.0.0.0:8085
    ports:
      - 8085:8085
  gcloud-pubsub-emulator_prep:
    image: martynas/gcloud-pubsub-client
    links:
      - "gcloud-pubsub-emulator"
    environment:
      - "PUBSUB_PROJECT_ID=test"
      - "PUBSUB_EMULATOR_HOST=gcloud-pubsub-emulator:8085"
    entrypoint: ""
    command: >
      bash -c "
        python publisher.py test create scheduler-events &&
        python subscriber.py test create scheduler-events schedulerSubscription
      "

